# f1=open("file_1.txt","w")
# f1.write("hello world,i am poluri pradeeshna!here i am learning python")
# data=f1.read()
# print(data)
###
# f2=open("file_handling.txt", "w")
# data=f2.write("(hello)")
# data2=f2.write(" byee")
# data3=f2.write(" namaste")
# data4=f2.close()
# print(data4)
####
# f3=open("pradeeshna.txt","w")
# f4=open("pradeeshna.txt","r")
# writing=f3.write("writing name as pradeeshna poluri")
# closing=f3.close()
# reading=f4.read()
# closing=f4.close()
# print(writing)
# print(reading)
# print(closing)
