# f1=open("file_1.txt","w")
# f1.write("hello world,i am poluri pradeeshna!here i am learning python")
# data=f1.read()
# print(data)
f2=open("abstraction_methods.py","w")
data=f2.write("hello")
data2=f2.write(" byee")
data3=f2.close()
print(data3)
